baseURL = "/"
languageCode = "en-us"
title = "Work in Progress"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = "UA-101213116-1"

[params]
    author = "Carmel Gafa"
    description = "Carmel Gafa"
    githubUsername = "#"
    accent = "#060608"
    showBorder = true
    backgroundColor = "#f7f8fa"
    font = "Raleway"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/carmelgafa/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/carmel-gafa-200aa37/"
    name = "fab fa-linkedin"
    weight = 4

