baseURL = "/"
languageCode = "en-us"
title = ""
theme = "minimal"
disqusShortname = "carmelgafa-com-1"
googleAnalytics = "307561524"

[params]
    author = "Carmel Gafa"
    description = "Carmel Gafa Homepage"
    githubUsername = "#"
    accent = "#660608"
    showBorder = true
    backgroundColor = "#f7f8fa"
    font = "Raleway"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Tech Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Tech Projects"
    weight = 4

[[menu.main]]
    url = "/misc/"
    name = "Non-Tech"
    weight = 5


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:carmelafa@hotmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/carmelgafa/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/carmel-gafa-200aa37/"
    name = "fab fa-linkedin"
    weight = 4

